LEAGUES_TO_PATH = {
    'nba': 'http://www.basketball-reference.com/leagues/NBA_{0}_games.html',
    'acb': 'http://www.basketball-reference.com/euro/spain-liga-acb/{0}-schedule.html',
    'lnb': 'http://www.basketball-reference.com/euro/france-lnb-pro-a/{0}-schedule.html',
    'seriea': 'http://www.basketball-reference.com/euro/italy-basket-serie-a/{0}-schedule.html',
    'greek': 'http://www.basketball-reference.com/euro/greek-basket-league/{0}-schedule.html',
}


USER_AGENTS = [
    'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.1',
    'Mozilla/5.0 (Windows NT 6.3; rv:36.0) Gecko/20100101 Firefox/36.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10; rv:33.0) Gecko/20100101 Firefox/33.0',
    'Mozilla/5.0 (X11; U; Linux x86_64; it-it) AppleWebKit/534.26+ (KHTML, like Gecko) Ubuntu/11.04 Epiphany/2.30.6',
    'Mozilla/5.0 (X11; U; Linux x86_64; fr-FR) AppleWebKit/534.7 (KHTML, like Gecko) Epiphany/2.30.6 Safari/534.7',
    'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.1 Safari/537.36',
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36',
    'Opera/9.80 (X11; Linux i686; Ubuntu/14.10) Presto/2.12.388 Version/12.16',
    'Opera/9.80 (Windows NT 6.0) Presto/2.12.388 Version/12.14',
]


TEAMS = {
    'Atlanta-2007': 'Atlanta Hawks',
    'Atlanta-2008': 'Atlanta Hawks',
    'Atlanta-2009': 'Atlanta Hawks',
    'Atlanta-2010': 'Atlanta Hawks',
    'Atlanta-2011': 'Atlanta Hawks',
    'Atlanta-2012': 'Atlanta Hawks',
    'Atlanta-2013': 'Atlanta Hawks',
    'Atlanta-2014': 'Atlanta Hawks',
    'Atlanta-2015': 'Atlanta Hawks',
    'Atlanta-2016': 'Atlanta Hawks',
    'Boston-2007': 'Boston Celtics',
    'Boston-2008': 'Boston Celtics',
    'Boston-2009': 'Boston Celtics',
    'Boston-2010': 'Boston Celtics',
    'Boston-2011': 'Boston Celtics',
    'Boston-2012': 'Boston Celtics',
    'Boston-2013': 'Boston Celtics',
    'Boston-2014': 'Boston Celtics',
    'Boston-2015': 'Boston Celtics',
    'Boston-2016': 'Boston Celtics',
    'Brooklyn-2007': 'Brooklyn Nets',
    'Brooklyn-2008': 'Brooklyn Nets',
    'Brooklyn-2009': 'Brooklyn Nets',
    'Brooklyn-2010': 'Brooklyn Nets',
    'Brooklyn-2011': 'Brooklyn Nets',
    'Brooklyn-2012': 'Brooklyn Nets',
    'Brooklyn-2013': 'Brooklyn Nets',
    'Brooklyn-2014': 'Brooklyn Nets',
    'Brooklyn-2015': 'Brooklyn Nets',
    'Brooklyn-2016': 'Brooklyn Nets',
    'Charlotte-2007': 'Charlotte Bobcats',
    'Charlotte-2008': 'Charlotte Bobcats',
    'Charlotte-2009': 'Charlotte Bobcats',
    'Charlotte-2010': 'Charlotte Bobcats',
    'Charlotte-2011': 'Charlotte Bobcats',
    'Charlotte-2012': 'Charlotte Bobcats',
    'Charlotte-2013': 'Charlotte Bobcats',
    'Charlotte-2014': 'Charlotte Bobcats',
    'Charlotte-2015': 'Charlotte Hornets',
    'Charlotte-2016': 'Charlotte Hornets',
    'Chicago-2007': 'Chicago Bulls',
    'Chicago-2008': 'Chicago Bulls',
    'Chicago-2009': 'Chicago Bulls',
    'Chicago-2010': 'Chicago Bulls',
    'Chicago-2011': 'Chicago Bulls',
    'Chicago-2012': 'Chicago Bulls',
    'Chicago-2013': 'Chicago Bulls',
    'Chicago-2014': 'Chicago Bulls',
    'Chicago-2015': 'Chicago Bulls',
    'Chicago-2016': 'Chicago Bulls',
    'Cleveland-2007': 'Cleveland Cavaliers',
    'Cleveland-2008': 'Cleveland Cavaliers',
    'Cleveland-2009': 'Cleveland Cavaliers',
    'Cleveland-2010': 'Cleveland Cavaliers',
    'Cleveland-2011': 'Cleveland Cavaliers',
    'Cleveland-2012': 'Cleveland Cavaliers',
    'Cleveland-2013': 'Cleveland Cavaliers',
    'Cleveland-2014': 'Cleveland Cavaliers',
    'Cleveland-2015': 'Cleveland Cavaliers',
    'Cleveland-2016': 'Cleveland Cavaliers',
    'Dallas-2007': 'Dallas Mavericks',
    'Dallas-2008': 'Dallas Mavericks',
    'Dallas-2009': 'Dallas Mavericks',
    'Dallas-2010': 'Dallas Mavericks',
    'Dallas-2011': 'Dallas Mavericks',
    'Dallas-2012': 'Dallas Mavericks',
    'Dallas-2013': 'Dallas Mavericks',
    'Dallas-2014': 'Dallas Mavericks',
    'Dallas-2015': 'Dallas Mavericks',
    'Dallas-2016': 'Dallas Mavericks',
    'Denver-2007': 'Denver Nuggets',
    'Denver-2008': 'Denver Nuggets',
    'Denver-2009': 'Denver Nuggets',
    'Denver-2010': 'Denver Nuggets',
    'Denver-2011': 'Denver Nuggets',
    'Denver-2012': 'Denver Nuggets',
    'Denver-2013': 'Denver Nuggets',
    'Denver-2014': 'Denver Nuggets',
    'Denver-2015': 'Denver Nuggets',
    'Denver-2016': 'Denver Nuggets',
    'Detroit-2007': 'Detroit Pistons',
    'Detroit-2008': 'Detroit Pistons',
    'Detroit-2009': 'Detroit Pistons',
    'Detroit-2010': 'Detroit Pistons',
    'Detroit-2011': 'Detroit Pistons',
    'Detroit-2012': 'Detroit Pistons',
    'Detroit-2013': 'Detroit Pistons',
    'Detroit-2014': 'Detroit Pistons',
    'Detroit-2015': 'Detroit Pistons',
    'Detroit-2016': 'Detroit Pistons',
    'Golden State-2007': 'Golden State Warriors',
    'Golden State-2008': 'Golden State Warriors',
    'Golden State-2009': 'Golden State Warriors',
    'Golden State-2010': 'Golden State Warriors',
    'Golden State-2011': 'Golden State Warriors',
    'Golden State-2012': 'Golden State Warriors',
    'Golden State-2013': 'Golden State Warriors',
    'Golden State-2014': 'Golden State Warriors',
    'Golden State-2015': 'Golden State Warriors',
    'Golden State-2016': 'Golden State Warriors',
    'Houston-2007': 'Houston Rockets',
    'Houston-2008': 'Houston Rockets',
    'Houston-2009': 'Houston Rockets',
    'Houston-2010': 'Houston Rockets',
    'Houston-2011': 'Houston Rockets',
    'Houston-2012': 'Houston Rockets',
    'Houston-2013': 'Houston Rockets',
    'Houston-2014': 'Houston Rockets',
    'Houston-2015': 'Houston Rockets',
    'Houston-2016': 'Houston Rockets',
    'Indiana-2007': 'Indiana Pacers',
    'Indiana-2008': 'Indiana Pacers',
    'Indiana-2009': 'Indiana Pacers',
    'Indiana-2010': 'Indiana Pacers',
    'Indiana-2011': 'Indiana Pacers',
    'Indiana-2012': 'Indiana Pacers',
    'Indiana-2013': 'Indiana Pacers',
    'Indiana-2014': 'Indiana Pacers',
    'Indiana-2015': 'Indiana Pacers',
    'Indiana-2016': 'Indiana Pacers',
    'L.A. Clippers-2007': 'Los Angeles Clippers',
    'L.A. Clippers-2008': 'Los Angeles Clippers',
    'L.A. Clippers-2009': 'Los Angeles Clippers',
    'L.A. Clippers-2010': 'Los Angeles Clippers',
    'L.A. Clippers-2011': 'Los Angeles Clippers',
    'L.A. Clippers-2012': 'Los Angeles Clippers',
    'L.A. Clippers-2013': 'Los Angeles Clippers',
    'L.A. Clippers-2014': 'Los Angeles Clippers',
    'L.A. Clippers-2015': 'Los Angeles Clippers',
    'L.A. Clippers-2016': 'Los Angeles Clippers',
    'L.A. Lakers-2007': 'Los Angeles Lakers',
    'L.A. Lakers-2008': 'Los Angeles Lakers',
    'L.A. Lakers-2009': 'Los Angeles Lakers',
    'L.A. Lakers-2010': 'Los Angeles Lakers',
    'L.A. Lakers-2011': 'Los Angeles Lakers',
    'L.A. Lakers-2012': 'Los Angeles Lakers',
    'L.A. Lakers-2013': 'Los Angeles Lakers',
    'L.A. Lakers-2014': 'Los Angeles Lakers',
    'L.A. Lakers-2015': 'Los Angeles Lakers',
    'L.A. Lakers-2016': 'Los Angeles Lakers',
    'Memphis-2007': 'Memphis Grizzlies',
    'Memphis-2008': 'Memphis Grizzlies',
    'Memphis-2009': 'Memphis Grizzlies',
    'Memphis-2010': 'Memphis Grizzlies',
    'Memphis-2011': 'Memphis Grizzlies',
    'Memphis-2012': 'Memphis Grizzlies',
    'Memphis-2013': 'Memphis Grizzlies',
    'Memphis-2014': 'Memphis Grizzlies',
    'Memphis-2015': 'Memphis Grizzlies',
    'Memphis-2016': 'Memphis Grizzlies',
    'Miami-2007': 'Miami Heat',
    'Miami-2008': 'Miami Heat',
    'Miami-2009': 'Miami Heat',
    'Miami-2010': 'Miami Heat',
    'Miami-2011': 'Miami Heat',
    'Miami-2012': 'Miami Heat',
    'Miami-2013': 'Miami Heat',
    'Miami-2014': 'Miami Heat',
    'Miami-2015': 'Miami Heat',
    'Miami-2016': 'Miami Heat',
    'Milwaukee-2007': 'Milwaukee Bucks',
    'Milwaukee-2008': 'Milwaukee Bucks',
    'Milwaukee-2009': 'Milwaukee Bucks',
    'Milwaukee-2010': 'Milwaukee Bucks',
    'Milwaukee-2011': 'Milwaukee Bucks',
    'Milwaukee-2012': 'Milwaukee Bucks',
    'Milwaukee-2013': 'Milwaukee Bucks',
    'Milwaukee-2014': 'Milwaukee Bucks',
    'Milwaukee-2015': 'Milwaukee Bucks',
    'Milwaukee-2016': 'Milwaukee Bucks',
    'Minnesota-2007': 'Minnesota Timberwolves',
    'Minnesota-2008': 'Minnesota Timberwolves',
    'Minnesota-2009': 'Minnesota Timberwolves',
    'Minnesota-2010': 'Minnesota Timberwolves',
    'Minnesota-2011': 'Minnesota Timberwolves',
    'Minnesota-2012': 'Minnesota Timberwolves',
    'Minnesota-2013': 'Minnesota Timberwolves',
    'Minnesota-2014': 'Minnesota Timberwolves',
    'Minnesota-2015': 'Minnesota Timberwolves',
    'Minnesota-2016': 'Minnesota Timberwolves',
    'New Jersey-2007': 'New Jersey Nets',
    'New Jersey-2008': 'New Jersey Nets',
    'New Jersey-2009': 'New Jersey Nets',
    'New Jersey-2010': 'New Jersey Nets',
    'New Jersey-2011': 'New Jersey Nets',
    'New Jersey-2012': 'New Jersey Nets',
    'New Orleans-2007': 'New Orleans Hornets',
    'New Orleans-2008': 'New Orleans Hornets',
    'New Orleans-2009': 'New Orleans Hornets',
    'New Orleans-2010': 'New Orleans Hornets',
    'New Orleans-2011': 'New Orleans Hornets',
    'New Orleans-2012': 'New Orleans Hornets',
    'New Orleans-2013': 'New Orleans Hornets',
    'New Orleans-2014': 'New Orleans Pelicans',
    'New Orleans-2015': 'New Orleans Pelicans',
    'New Orleans-2016': 'New Orleans Pelicans',
    'New York-2007': 'New York Knicks',
    'New York-2008': 'New York Knicks',
    'New York-2009': 'New York Knicks',
    'New York-2010': 'New York Knicks',
    'New York-2011': 'New York Knicks',
    'New York-2012': 'New York Knicks',
    'New York-2013': 'New York Knicks',
    'New York-2014': 'New York Knicks',
    'New York-2015': 'New York Knicks',
    'New York-2016': 'New York Knicks',
    'Oklahoma City-2009': 'Oklahoma City Thunder',
    'Oklahoma City-2010': 'Oklahoma City Thunder',
    'Oklahoma City-2011': 'Oklahoma City Thunder',
    'Oklahoma City-2012': 'Oklahoma City Thunder',
    'Oklahoma City-2013': 'Oklahoma City Thunder',
    'Oklahoma City-2014': 'Oklahoma City Thunder',
    'Oklahoma City-2015': 'Oklahoma City Thunder',
    'Oklahoma City-2016': 'Oklahoma City Thunder',
    'Orlando-2007': 'Orlando Magic',
    'Orlando-2008': 'Orlando Magic',
    'Orlando-2009': 'Orlando Magic',
    'Orlando-2010': 'Orlando Magic',
    'Orlando-2011': 'Orlando Magic',
    'Orlando-2012': 'Orlando Magic',
    'Orlando-2013': 'Orlando Magic',
    'Orlando-2014': 'Orlando Magic',
    'Orlando-2015': 'Orlando Magic',
    'Orlando-2016': 'Orlando Magic',
    'Philadelphia-2007': 'Philadelphia 76ers',
    'Philadelphia-2008': 'Philadelphia 76ers',
    'Philadelphia-2009': 'Philadelphia 76ers',
    'Philadelphia-2010': 'Philadelphia 76ers',
    'Philadelphia-2011': 'Philadelphia 76ers',
    'Philadelphia-2012': 'Philadelphia 76ers',
    'Philadelphia-2013': 'Philadelphia 76ers',
    'Philadelphia-2014': 'Philadelphia 76ers',
    'Philadelphia-2015': 'Philadelphia 76ers',
    'Philadelphia-2016': 'Philadelphia 76ers',
    'Phoenix-2007': 'Phoenix Suns',
    'Phoenix-2008': 'Phoenix Suns',
    'Phoenix-2009': 'Phoenix Suns',
    'Phoenix-2010': 'Phoenix Suns',
    'Phoenix-2011': 'Phoenix Suns',
    'Phoenix-2012': 'Phoenix Suns',
    'Phoenix-2013': 'Phoenix Suns',
    'Phoenix-2014': 'Phoenix Suns',
    'Phoenix-2015': 'Phoenix Suns',
    'Phoenix-2016': 'Phoenix Suns',
    'Portland-2007': 'Portland Trail Blazers',
    'Portland-2008': 'Portland Trail Blazers',
    'Portland-2009': 'Portland Trail Blazers',
    'Portland-2010': 'Portland Trail Blazers',
    'Portland-2011': 'Portland Trail Blazers',
    'Portland-2012': 'Portland Trail Blazers',
    'Portland-2013': 'Portland Trail Blazers',
    'Portland-2014': 'Portland Trail Blazers',
    'Portland-2015': 'Portland Trail Blazers',
    'Portland-2016': 'Portland Trail Blazers',
    'Sacramento-2007': 'Sacramento Kings',
    'Sacramento-2008': 'Sacramento Kings',
    'Sacramento-2009': 'Sacramento Kings',
    'Sacramento-2010': 'Sacramento Kings',
    'Sacramento-2011': 'Sacramento Kings',
    'Sacramento-2012': 'Sacramento Kings',
    'Sacramento-2013': 'Sacramento Kings',
    'Sacramento-2014': 'Sacramento Kings',
    'Sacramento-2015': 'Sacramento Kings',
    'Sacramento-2016': 'Sacramento Kings',
    'San Antonio-2007': 'San Antonio Spurs',
    'San Antonio-2008': 'San Antonio Spurs',
    'San Antonio-2009': 'San Antonio Spurs',
    'San Antonio-2010': 'San Antonio Spurs',
    'San Antonio-2011': 'San Antonio Spurs',
    'San Antonio-2012': 'San Antonio Spurs',
    'San Antonio-2013': 'San Antonio Spurs',
    'San Antonio-2014': 'San Antonio Spurs',
    'San Antonio-2015': 'San Antonio Spurs',
    'San Antonio-2016': 'San Antonio Spurs',
    'Seattle-2007': 'Seattle SuperSonics',
    'Seattle-2008': 'Seattle SuperSonics',
    'Toronto-2007': 'Toronto Raptors',
    'Toronto-2008': 'Toronto Raptors',
    'Toronto-2009': 'Toronto Raptors',
    'Toronto-2010': 'Toronto Raptors',
    'Toronto-2011': 'Toronto Raptors',
    'Toronto-2012': 'Toronto Raptors',
    'Toronto-2013': 'Toronto Raptors',
    'Toronto-2014': 'Toronto Raptors',
    'Toronto-2015': 'Toronto Raptors',
    'Toronto-2016': 'Toronto Raptors',
    'Utah-2007': 'Utah Jazz',
    'Utah-2008': 'Utah Jazz',
    'Utah-2009': 'Utah Jazz',
    'Utah-2010': 'Utah Jazz',
    'Utah-2011': 'Utah Jazz',
    'Utah-2012': 'Utah Jazz',
    'Utah-2013': 'Utah Jazz',
    'Utah-2014': 'Utah Jazz',
    'Utah-2015': 'Utah Jazz',
    'Utah-2016': 'Utah Jazz',
    'Washington-2007': 'Washington Wizards',
    'Washington-2008': 'Washington Wizards',
    'Washington-2009': 'Washington Wizards',
    'Washington-2010': 'Washington Wizards',
    'Washington-2011': 'Washington Wizards',
    'Washington-2012': 'Washington Wizards',
    'Washington-2013': 'Washington Wizards',
    'Washington-2014': 'Washington Wizards',
    'Washington-2015': 'Washington Wizards',
    'Washington-2016': 'Washington Wizards',
}


TEAMS_TO_CITIES = {
    'Atlanta Hawks': 'Atlanta',
    'Boston Celtics': 'Boston',
    'Brooklyn Nets': 'Brooklyn',
    'Charlotte Bobcats': 'Charlotte',
    'Charlotte Hornets': 'Charlotte',
    'Chicago Bulls': 'Chicago',
    'Cleveland Cavaliers': 'Cleveland',
    'Dallas Mavericks': 'Dallas',
    'Denver Nuggets': 'Denver',
    'Detroit Pistons': 'Detroit',
    'Golden State Warriors': 'Oakland',
    'Houston Rockets': 'Houston',
    'Indiana Pacers': 'Indiana',
    'Los Angeles Clippers': 'Los Angeles',
    'Los Angeles Lakers': 'Los Angeles',
    'Memphis Grizzlies': 'Memphis',
    'Miami Heat': 'Miami',
    'Milwaukee Bucks': 'Milwaukee',
    'Minnesota Timberwolves': 'Minnesota',
    'New Jersey Nets': 'New Jersey',
    'New Orleans Hornets': 'New Orleans',
    'New Orleans Pelicans': 'New Orleans',
    'New Orleans/Oklahoma City Hornets': 'Oklahoma City',
    'New York Knicks': 'New York',
    'Oklahoma City Thunder': 'Oklahoma City',
    'Orlando Magic': 'Orlando',
    'Philadelphia 76ers': 'Philadelphia',
    'Phoenix Suns': 'Phoenix',
    'Portland Trail Blazers': 'Portland',
    'Sacramento Kings': 'Sacramento',
    'San Antonio Spurs': 'San Antonio',
    'Seattle SuperSonics': 'Seattle',
    'Toronto Raptors': 'Toronto',
    'Utah Jazz': 'Utah',
    'Vancouver Grizzlies': 'Vancouver',
    'Washington Wizards': 'Washington'
}


TEAMS_ABBRV = {
    'Atlanta Hawks': 'ATL',
    'Boston Celtics': 'BOS',
    'Brooklyn Nets': 'BRK',
    'Charlotte Bobcats': 'CHA',
    'Charlotte Hornets': 'CHO',
    'Chicago Bulls': 'CHI',
    'Cleveland Cavaliers': 'CLE',
    'Dallas Mavericks': 'DAL',
    'Denver Nuggets': 'DEN',
    'Detroit Pistons': 'DET',
    'Houston Rockets': 'HOU',
    'Indiana Pacers': 'IND',
    'Los Angeles Lakers': 'LAL',
    'Los Angeles Clippers': 'LAC',
    'Memphis Grizzlies': 'MEM',
    'Miami Heat': 'MIA',
    'Milwaukee Bucks': 'MIL',
    'Minnesota Timberwolves': 'MIN',
    'New Jersey Nets': 'NJN',
    'New Orleans Hornets': 'NOH',
    'New Orleans Pelicans': 'NOP',
    'New York Knicks': 'NYK',
    'Golden State Warriors': 'GSW',
    'Oklahoma City Thunder': 'OKC',
    'Orlando Magic': 'ORL',
    'Philadelphia 76ers': 'PHI',
    'Phoenix Suns': 'PHO',
    'Portland Trail Blazers': 'POR',
    'Sacramento Kings': 'SAC',
    'San Antonio Spurs': 'SAS',
    'Seattle SuperSonics': 'SEA',
    'Toronto Raptors': 'TOR',
    'Utah Jazz': 'UTA',
    'Vancouver Grizzlies': 'VAN',
    'Washington Wizards': 'WAS'
}


RAW_STATS = [
    'MP',
    'FG',
    'FGA',
    'PTS',
    'TWO',
    'TWOA',
    'THR',
    'THRA',
    'FT',
    'FTA',
    'ORB',
    'DRB',
    'TRB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PLUS_MINUS',
]


MONTHS = {
    'January': 1,
    'Jan': 1,
    'February': 2,
    'Feb': 2,
    'March': 3,
    'Mar': 3,
    'April': 4,
    'Apr': 4,
    'May': 5,
    'June': 6,
    'Jun': 6,
    'July': 7,
    'Jul': 7,
    'August': 8,
    'Aug': 8,
    'September': 9,
    'Sep': 9,
    'October': 10,
    'Oct': 10,
    'November': 11,
    'Nov': 11,
    'December': 12,
    'Dec': 12,
}


POSITIONS = {
    'Point guard': 'PG',
    'Guard': 'PG',
    'Shooting guard': 'SG',
    'Small forward': 'SF',
    'Power forward': 'PF',
    'Forward': 'F',
    'Center': 'C',
}


PLS_HEADERS = {
    'Weight': 'weight',
    'Wt': 'weight',
    'Player': 'name',
    '': '',
    'College': 'college',
    'Ht': 'height',
    'Height': 'height',
    'Exp': 'experience',
    'Pos': 'position',
    'Birth Date': 'birth_date',
    'No.': 'number',
    'Class': 'class',
    'Hometown': 'hometown',
    'High School': 'high_school',
    'Summary': 'summary',
    '#': 'number',
}


LEAGUES_TO_COUNTRIES = {
    'nba': 'united_states',
    'ncaa': 'united_states',
    'acb': 'spain',
    'lnb': 'france',
    'seriea': 'italy',
    'greek': 'greek',
}


LEAGUES_TO_PATH = {
    'nba': 'http://www.basketball-reference.com/leagues/NBA_{0}_games.html',
    'acb': 'http://www.basketball-reference.com/euro/spain-liga-acb/{0}-schedule.html',
    'lnb': 'http://www.basketball-reference.com/euro/france-lnb-pro-a/{0}-schedule.html',
    'seriea': 'http://www.basketball-reference.com/euro/italy-basket-serie-a/{0}-schedule.html',
    'greek': 'http://www.basketball-reference.com/euro/greek-basket-league/{0}-schedule.html',
}


COLLEGES_PATHS = {
    'Abilene Christian Wildcats': '/cbb/schools/abilene-christian/',
    'Air Force Falcons': '/cbb/schools/air-force/',
    'Akron Zips': '/cbb/schools/akron/',
    'Alabama A&M Bulldogs': '/cbb/schools/alabama-am/',
    'Alabama Crimson Tide': '/cbb/schools/alabama/',
    'Alabama State Hornets': '/cbb/schools/alabama-state/',
    'Alabama-Birmingham Blazers': '/cbb/schools/alabama-birmingham/',
    'Albany (NY) Great Danes': '/cbb/schools/albany-ny/',
    'Alcorn State Braves': '/cbb/schools/alcorn-state/',
    'American Eagles': '/cbb/schools/american/',
    'Appalachian State Mountaineers': '/cbb/schools/appalachian-state/',
    'Arizona State Sun Devils': '/cbb/schools/arizona-state/',
    'Arizona Wildcats': '/cbb/schools/arizona/',
    'Arkansas Razorbacks': '/cbb/schools/arkansas/',
    'Arkansas State Red Wolves': '/cbb/schools/arkansas-state/',
    'Arkansas-Little Rock Trojans': '/cbb/schools/arkansas-little-rock/',
    'Arkansas-Pine Bluff Golden Lions': '/cbb/schools/arkansas-pine-bluff/',
    'Army Black Knights': '/cbb/schools/army/',
    'Auburn Tigers': '/cbb/schools/auburn/',
    'Austin Peay Governors': '/cbb/schools/austin-peay/',
    'Ball State Cardinals': '/cbb/schools/ball-state/',
    'Baylor Bears': '/cbb/schools/baylor/',
    'Belmont Bruins': '/cbb/schools/belmont/',
    'Bethune-Cookman Wildcats': '/cbb/schools/bethune-cookman/',
    'Binghamton Bearcats': '/cbb/schools/binghamton/',
    'Boise State Broncos': '/cbb/schools/boise-state/',
    'Boston College Eagles': '/cbb/schools/boston-college/',
    'Boston University Terriers': '/cbb/schools/boston-university/',
    'Bowling Green State Falcons': '/cbb/schools/bowling-green-state/',
    'Bradley Braves': '/cbb/schools/bradley/',
    'Brigham Young Cougars': '/cbb/schools/brigham-young/',
    'Brown Bears': '/cbb/schools/brown/',
    'Bryant Bulldogs': '/cbb/schools/bryant/',
    'Bucknell Bison': '/cbb/schools/bucknell/',
    'Buffalo Bulls': '/cbb/schools/buffalo/',
    'Butler Bulldogs': '/cbb/schools/butler/',
    'Cal Poly Mustangs': '/cbb/schools/cal-poly/',
    'Cal State Bakersfield Roadrunners': '/cbb/schools/cal-state-bakersfield/',
    'Cal State Fullerton Titans': '/cbb/schools/cal-state-fullerton/',
    'Cal State Northridge Matadors': '/cbb/schools/cal-state-northridge/',
    'Campbell Fighting Camels': '/cbb/schools/campbell/',
    'Canisius Golden Griffins': '/cbb/schools/canisius/',
    'Central Arkansas Bears': '/cbb/schools/central-arkansas/',
    'Central Connecticut State Blue Devils': '/cbb/schools/central-connecticut-state/',
    'Central Florida Knights': '/cbb/schools/central-florida/',
    'Central Michigan Chippewas': '/cbb/schools/central-michigan/',
    'Charleston Southern Buccaneers': '/cbb/schools/charleston-southern/',
    'Charlotte 49ers': '/cbb/schools/charlotte/',
    'Chattanooga Mocs': '/cbb/schools/chattanooga/',
    'Chicago State Cougars': '/cbb/schools/chicago-state/',
    'Cincinnati Bearcats': '/cbb/schools/cincinnati/',
    'Citadel Bulldogs': '/cbb/schools/citadel/',
    'Clemson Tigers': '/cbb/schools/clemson/',
    'Cleveland State Vikings': '/cbb/schools/cleveland-state/',
    'Coastal Carolina Chanticleers': '/cbb/schools/coastal-carolina/',
    'Colgate Raiders': '/cbb/schools/colgate/',
    'College of Charleston Cougars': '/cbb/schools/college-of-charleston/',
    'Colorado Buffaloes': '/cbb/schools/colorado/',
    'Colorado State Rams': '/cbb/schools/colorado-state/',
    'Columbia Lions': '/cbb/schools/columbia/',
    'Connecticut Huskies': '/cbb/schools/connecticut/',
    'Coppin State Eagles': '/cbb/schools/coppin-state/',
    'Cornell Big Red': '/cbb/schools/cornell/',
    'Creighton Bluejays': '/cbb/schools/creighton/',
    'Dartmouth Big Green': '/cbb/schools/dartmouth/',
    'Davidson Wildcats': '/cbb/schools/davidson/',
    'Dayton Flyers': '/cbb/schools/dayton/',
    'DePaul Blue Demons': '/cbb/schools/depaul/',
    "Delaware Fightin' Blue Hens": '/cbb/schools/delaware/',
    'Delaware State Hornets': '/cbb/schools/delaware-state/',
    'Denver Pioneers': '/cbb/schools/denver/',
    'Detroit Mercy Titans': '/cbb/schools/detroit-mercy/',
    'Drake Bulldogs': '/cbb/schools/drake/',
    'Drexel Dragons': '/cbb/schools/drexel/',
    'Duke Blue Devils': '/cbb/schools/duke/',
    'Duquesne Dukes': '/cbb/schools/duquesne/',
    'East Carolina Pirates': '/cbb/schools/east-carolina/',
    'East Tennessee State Buccaneers': '/cbb/schools/east-tennessee-state/',
    'Eastern Illinois Panthers': '/cbb/schools/eastern-illinois/',
    'Eastern Kentucky Colonels': '/cbb/schools/eastern-kentucky/',
    'Eastern Michigan Eagles': '/cbb/schools/eastern-michigan/',
    'Eastern Washington Eagles': '/cbb/schools/eastern-washington/',
    'Elon Phoenix': '/cbb/schools/elon/',
    'Evansville Purple Aces': '/cbb/schools/evansville/',
    'Fairfield Stags': '/cbb/schools/fairfield/',
    'Fairleigh Dickinson Knights': '/cbb/schools/fairleigh-dickinson/',
    'Florida A&M Rattlers': '/cbb/schools/florida-am/',
    'Florida Atlantic Owls': '/cbb/schools/florida-atlantic/',
    'Florida Gators': '/cbb/schools/florida/',
    'Florida Gulf Coast Eagles': '/cbb/schools/florida-gulf-coast/',
    'Florida International Panthers': '/cbb/schools/florida-international/',
    'Florida State Seminoles': '/cbb/schools/florida-state/',
    'Fordham Rams': '/cbb/schools/fordham/',
    'Fresno State Bulldogs': '/cbb/schools/fresno-state/',
    'Furman Paladins': '/cbb/schools/furman/',
    "Gardner-Webb Runnin' Bulldogs": '/cbb/schools/gardner-webb/',
    'George Mason Patriots': '/cbb/schools/george-mason/',
    'George Washington Colonials': '/cbb/schools/george-washington/',
    'Georgetown Hoyas': '/cbb/schools/georgetown/',
    'Georgia Bulldogs': '/cbb/schools/georgia/',
    'Georgia Southern Eagles': '/cbb/schools/georgia-southern/',
    'Georgia State Panthers': '/cbb/schools/georgia-state/',
    'Georgia Tech Yellow Jackets': '/cbb/schools/georgia-tech/',
    'Gonzaga Bulldogs': '/cbb/schools/gonzaga/',
    'Grambling Tigers': '/cbb/schools/grambling/',
    'Grand Canyon Antelopes': '/cbb/schools/grand-canyon/',
    'Green Bay Phoenix': '/cbb/schools/green-bay/',
    'Hampton Pirates': '/cbb/schools/hampton/',
    'Hartford Hawks': '/cbb/schools/hartford/',
    'Harvard Crimson': '/cbb/schools/harvard/',
    'Hawaii Warriors': '/cbb/schools/hawaii/',
    'High Point Panthers': '/cbb/schools/high-point/',
    'Hofstra Pride': '/cbb/schools/hofstra/',
    'Holy Cross Crusaders': '/cbb/schools/holy-cross/',
    'Houston Baptist Huskies': '/cbb/schools/houston-baptist/',
    'Houston Cougars': '/cbb/schools/houston/',
    'Howard Bison': '/cbb/schools/howard/',
    'IPFW Mastodons': '/cbb/schools/ipfw/',
    'IUPUI Jaguars': '/cbb/schools/iupui/',
    'Idaho State Bengals': '/cbb/schools/idaho-state/',
    'Idaho Vandals': '/cbb/schools/idaho/',
    'Illinois Fighting Illini': '/cbb/schools/illinois/',
    'Illinois State Redbirds': '/cbb/schools/illinois-state/',
    'Illinois-Chicago Flames': '/cbb/schools/illinois-chicago/',
    'Incarnate Word Cardinals': '/cbb/schools/incarnate-word/',
    'Indiana Hoosiers': '/cbb/schools/indiana/',
    'Indiana State Sycamores': '/cbb/schools/indiana-state/',
    'Iona Gaels': '/cbb/schools/iona/',
    'Iowa Hawkeyes': '/cbb/schools/iowa/',
    'Iowa State Cyclones': '/cbb/schools/iowa-state/',
    'Jackson State Tigers': '/cbb/schools/jackson-state/',
    'Jacksonville Dolphins': '/cbb/schools/jacksonville/',
    'Jacksonville State Gamecocks': '/cbb/schools/jacksonville-state/',
    'James Madison Dukes': '/cbb/schools/james-madison/',
    'Kansas Jayhawks': '/cbb/schools/kansas/',
    'Kansas State Wildcats': '/cbb/schools/kansas-state/',
    'Kennesaw State Owls': '/cbb/schools/kennesaw-state/',
    'Kent State Golden Flashes': '/cbb/schools/kent-state/',
    'Kentucky Wildcats': '/cbb/schools/kentucky/',
    'La Salle Explorers': '/cbb/schools/la-salle/',
    'Lafayette Leopards': '/cbb/schools/lafayette/',
    'Lamar Cardinals': '/cbb/schools/lamar/',
    'Lehigh Mountain Hawks': '/cbb/schools/lehigh/',
    'Liberty Flames': '/cbb/schools/liberty/',
    'Lipscomb Bisons': '/cbb/schools/lipscomb/',
    'Long Beach State 49ers': '/cbb/schools/long-beach-state/',
    'Long Island University Blackbirds': '/cbb/schools/long-island-university/',
    'Longwood Lancers': '/cbb/schools/longwood/',
    'Louisiana State Fighting Tigers': '/cbb/schools/louisiana-state/',
    'Louisiana Tech Bulldogs': '/cbb/schools/louisiana-tech/',
    "Louisiana-Lafayette Ragin' Cajuns": '/cbb/schools/louisiana-lafayette/',
    'Louisiana-Monroe Warhawks': '/cbb/schools/louisiana-monroe/',
    'Louisville Cardinals': '/cbb/schools/louisville/',
    'Loyola (IL) Ramblers': '/cbb/schools/loyola-il/',
    'Loyola (MD) Greyhounds': '/cbb/schools/loyola-md/',
    'Loyola Marymount Lions': '/cbb/schools/loyola-marymount/',
    'Maine Black Bears': '/cbb/schools/maine/',
    'Manhattan Jaspers': '/cbb/schools/manhattan/',
    'Marist Red Foxes': '/cbb/schools/marist/',
    'Marquette Golden Eagles': '/cbb/schools/marquette/',
    'Marshall Thundering Herd': '/cbb/schools/marshall/',
    'Maryland Terrapins': '/cbb/schools/maryland/',
    'Maryland-Baltimore County Retrievers': '/cbb/schools/maryland-baltimore-county/',
    'Maryland-Eastern Shore Hawks': '/cbb/schools/maryland-eastern-shore/',
    'Massachusetts Minutemen': '/cbb/schools/massachusetts/',
    'Massachusetts-Lowell River Hawks': '/cbb/schools/massachusetts-lowell/',
    'McNeese State Cowboys': '/cbb/schools/mcneese-state/',
    'Memphis Tigers': '/cbb/schools/memphis/',
    'Mercer Bears': '/cbb/schools/mercer/',
    'Miami (FL) Hurricanes': '/cbb/schools/miami-fl/',
    'Miami (OH) RedHawks': '/cbb/schools/miami-oh/',
    'Michigan State Spartans': '/cbb/schools/michigan-state/',
    'Michigan Wolverines': '/cbb/schools/michigan/',
    'Middle Tennessee Blue Raiders': '/cbb/schools/middle-tennessee/',
    'Milwaukee Panthers': '/cbb/schools/milwaukee/',
    'Minnesota Golden Gophers': '/cbb/schools/minnesota/',
    'Mississippi Rebels': '/cbb/schools/mississippi/',
    'Mississippi State Bulldogs': '/cbb/schools/mississippi-state/',
    'Mississippi Valley State Delta Devils': '/cbb/schools/mississippi-valley-state/',
    'Missouri State Bears': '/cbb/schools/missouri-state/',
    'Missouri Tigers': '/cbb/schools/missouri/',
    'Missouri-Kansas City Kangaroos': '/cbb/schools/missouri-kansas-city/',
    'Monmouth Hawks': '/cbb/schools/monmouth/',
    'Montana Grizzlies': '/cbb/schools/montana/',
    'Montana State Bobcats': '/cbb/schools/montana-state/',
    'Morehead State Eagles': '/cbb/schools/morehead-state/',
    'Morgan State Bears': '/cbb/schools/morgan-state/',
    "Mount St. Mary's Mountaineers": '/cbb/schools/mount-st-marys/',
    'Murray State Racers': '/cbb/schools/murray-state/',
    'NJIT Highlanders': '/cbb/schools/njit/',
    'Navy Midshipmen': '/cbb/schools/navy/',
    'Nebraska Cornhuskers': '/cbb/schools/nebraska/',
    'Nebraska-Omaha Mavericks': '/cbb/schools/nebraska-omaha/',
    'Nevada Wolf Pack': '/cbb/schools/nevada/',
    'Nevada-Las Vegas Rebels': '/cbb/schools/nevada-las-vegas/',
    'New Hampshire Wildcats': '/cbb/schools/new-hampshire/',
    'New Mexico Lobos': '/cbb/schools/new-mexico/',
    'New Mexico State Aggies': '/cbb/schools/new-mexico-state/',
    'New Orleans Privateers': '/cbb/schools/new-orleans/',
    'Niagara Purple Eagles': '/cbb/schools/niagara/',
    'Nicholls State Colonels': '/cbb/schools/nicholls-state/',
    'Norfolk State Spartans': '/cbb/schools/norfolk-state/',
    'North Carolina A&T Aggies': '/cbb/schools/north-carolina-at/',
    'North Carolina Central Eagles': '/cbb/schools/north-carolina-central/',
    'North Carolina State Wolfpack': '/cbb/schools/north-carolina-state/',
    'North Carolina Tar Heels': '/cbb/schools/north-carolina/',
    'North Carolina-Asheville Bulldogs': '/cbb/schools/north-carolina-asheville/',
    'North Carolina-Greensboro Spartans': '/cbb/schools/north-carolina-greensboro/',
    'North Carolina-Wilmington Seahawks': '/cbb/schools/north-carolina-wilmington/',
    'North Dakota State Bison': '/cbb/schools/north-dakota-state/',
    'North Dakota UND': '/cbb/schools/north-dakota/',
    'North Florida Ospreys': '/cbb/schools/north-florida/',
    'North Texas Mean Green': '/cbb/schools/north-texas/',
    'Northeastern Huskies': '/cbb/schools/northeastern/',
    'Northern Arizona Lumberjacks': '/cbb/schools/northern-arizona/',
    'Northern Colorado Bears': '/cbb/schools/northern-colorado/',
    'Northern Illinois Huskies': '/cbb/schools/northern-illinois/',
    'Northern Iowa Panthers': '/cbb/schools/northern-iowa/',
    'Northern Kentucky Norse': '/cbb/schools/northern-kentucky/',
    'Northwestern State Demons': '/cbb/schools/northwestern-state/',
    'Northwestern Wildcats': '/cbb/schools/northwestern/',
    'Notre Dame Fighting Irish': '/cbb/schools/notre-dame/',
    'Oakland Golden Grizzlies': '/cbb/schools/oakland/',
    'Ohio Bobcats': '/cbb/schools/ohio/',
    'Ohio State Buckeyes': '/cbb/schools/ohio-state/',
    'Oklahoma Sooners': '/cbb/schools/oklahoma/',
    'Oklahoma State Cowboys': '/cbb/schools/oklahoma-state/',
    'Old Dominion Monarchs': '/cbb/schools/old-dominion/',
    'Oral Roberts Golden Eagles': '/cbb/schools/oral-roberts/',
    'Oregon Ducks': '/cbb/schools/oregon/',
    'Oregon State Beavers': '/cbb/schools/oregon-state/',
    'Pacific Tigers': '/cbb/schools/pacific/',
    'Penn State Nittany Lions': '/cbb/schools/penn-state/',
    'Pennsylvania Quakers': '/cbb/schools/pennsylvania/',
    'Pepperdine Waves': '/cbb/schools/pepperdine/',
    'Pittsburgh Panthers': '/cbb/schools/pittsburgh/',
    'Portland Pilots': '/cbb/schools/portland/',
    'Portland State Vikings': '/cbb/schools/portland-state/',
    'Prairie View Panthers': '/cbb/schools/prairie-view/',
    'Presbyterian Blue Hose': '/cbb/schools/presbyterian/',
    'Princeton Tigers': '/cbb/schools/princeton/',
    'Providence Friars': '/cbb/schools/providence/',
    'Purdue Boilermakers': '/cbb/schools/purdue/',
    'Quinnipiac Bobcats': '/cbb/schools/quinnipiac/',
    'Radford Highlanders': '/cbb/schools/radford/',
    'Rhode Island Rams': '/cbb/schools/rhode-island/',
    'Rice Owls': '/cbb/schools/rice/',
    'Richmond Spiders': '/cbb/schools/richmond/',
    'Rider Broncs': '/cbb/schools/rider/',
    'Robert Morris Colonials': '/cbb/schools/robert-morris/',
    'Rutgers Scarlet Knights': '/cbb/schools/rutgers/',
    'Sacramento State Hornets': '/cbb/schools/sacramento-state/',
    'Sacred Heart Pioneers': '/cbb/schools/sacred-heart/',
    'Saint Francis (PA) Red Flash': '/cbb/schools/saint-francis-pa/',
    "Saint Joseph's Hawks": '/cbb/schools/saint-josephs/',
    'Saint Louis Billikens': '/cbb/schools/saint-louis/',
    "Saint Mary's (CA) Gaels": '/cbb/schools/saint-marys-ca/',
    "Saint Peter's Peacocks": '/cbb/schools/saint-peters/',
    'Sam Houston State Bearkats': '/cbb/schools/sam-houston-state/',
    'Samford Bulldogs': '/cbb/schools/samford/',
    'San Diego State Aztecs': '/cbb/schools/san-diego-state/',
    'San Diego Toreros': '/cbb/schools/san-diego/',
    'San Francisco Dons': '/cbb/schools/san-francisco/',
    'San Jose State Spartans': '/cbb/schools/san-jose-state/',
    'Santa Clara Broncos': '/cbb/schools/santa-clara/',
    'Savannah State Tigers': '/cbb/schools/savannah-state/',
    'Seattle Redhawks': '/cbb/schools/seattle/',
    'Seton Hall Pirates': '/cbb/schools/seton-hall/',
    'Siena Saints': '/cbb/schools/siena/',
    'South Alabama Jaguars': '/cbb/schools/south-alabama/',
    'South Carolina Gamecocks': '/cbb/schools/south-carolina/',
    'South Carolina State Bulldogs': '/cbb/schools/south-carolina-state/',
    'South Carolina Upstate Spartans': '/cbb/schools/south-carolina-upstate/',
    'South Dakota Coyotes': '/cbb/schools/south-dakota/',
    'South Dakota State Jackrabbits': '/cbb/schools/south-dakota-state/',
    'South Florida Bulls': '/cbb/schools/south-florida/',
    'Southeast Missouri State Redhawks': '/cbb/schools/southeast-missouri-state/',
    'Southeastern Louisiana Lions': '/cbb/schools/southeastern-louisiana/',
    'Southern California Trojans': '/cbb/schools/southern-california/',
    'Southern Illinois Salukis': '/cbb/schools/southern-illinois/',
    'Southern Illinois-Edwardsville Cougars': '/cbb/schools/southern-illinois-edwardsville/',
    'Southern Jaguars': '/cbb/schools/southern/',
    'Southern Methodist Mustangs': '/cbb/schools/southern-methodist/',
    'Southern Mississippi Golden Eagles': '/cbb/schools/southern-mississippi/',
    'Southern Utah Thunderbirds': '/cbb/schools/southern-utah/',
    'St. Bonaventure Bonnies': '/cbb/schools/st-bonaventure/',
    'St. Francis (NY) Terriers': '/cbb/schools/st-francis-ny/',
    "St. John's (NY) Red Storm": '/cbb/schools/st-johns-ny/',
    'Stanford Cardinal': '/cbb/schools/stanford/',
    'Stephen F. Austin Lumberjacks': '/cbb/schools/stephen-f-austin/',
    'Stetson Hatters': '/cbb/schools/stetson/',
    'Stony Brook Seawolves': '/cbb/schools/stony-brook/',
    'Syracuse Orange': '/cbb/schools/syracuse/',
    'Temple Owls': '/cbb/schools/temple/',
    'Tennessee State Tigers': '/cbb/schools/tennessee-state/',
    'Tennessee Tech Golden Eagles': '/cbb/schools/tennessee-tech/',
    'Tennessee Volunteers': '/cbb/schools/tennessee/',
    'Tennessee-Martin Skyhawks': '/cbb/schools/tennessee-martin/',
    'Texas A&M Aggies': '/cbb/schools/texas-am/',
    'Texas A&M-Corpus Christi Islanders': '/cbb/schools/texas-am-corpus-christi/',
    'Texas Christian Horned Frogs': '/cbb/schools/texas-christian/',
    'Texas Longhorns': '/cbb/schools/texas/',
    'Texas Southern Tigers': '/cbb/schools/texas-southern/',
    'Texas State Bobcats': '/cbb/schools/texas-state/',
    'Texas Tech Red Raiders': '/cbb/schools/texas-tech/',
    'Texas-Arlington Mavericks': '/cbb/schools/texas-arlington/',
    'Texas-El Paso Miners': '/cbb/schools/texas-el-paso/',
    'Texas-Rio Grande Valley Vaqueros': '/cbb/schools/texas-pan-american/',
    'Texas-San Antonio Roadrunners': '/cbb/schools/texas-san-antonio/',
    'Toledo Rockets': '/cbb/schools/toledo/',
    'Towson Tigers': '/cbb/schools/towson/',
    'Troy Trojans': '/cbb/schools/troy/',
    'Tulane Green Wave': '/cbb/schools/tulane/',
    'Tulsa Golden Hurricane': '/cbb/schools/tulsa/',
    'UC-Davis Aggies': '/cbb/schools/california-davis/',
    'UC-Irvine Anteaters': '/cbb/schools/california-irvine/',
    'UC-Riverside Highlanders': '/cbb/schools/california-riverside/',
    'UC-Santa Barbara Gauchos': '/cbb/schools/california-santa-barbara/',
    'UCLA Bruins': '/cbb/schools/ucla/',
    'University of California Golden Bears': '/cbb/schools/california/',
    'Utah State Aggies': '/cbb/schools/utah-state/',
    'Utah Utes': '/cbb/schools/utah/',
    'Utah Valley Wolverines': '/cbb/schools/utah-valley/',
    'Valparaiso Crusaders': '/cbb/schools/valparaiso/',
    'Vanderbilt Commodores': '/cbb/schools/vanderbilt/',
    'Vermont Catamounts': '/cbb/schools/vermont/',
    'Villanova Wildcats': '/cbb/schools/villanova/',
    'Virginia Cavaliers': '/cbb/schools/virginia/',
    'Virginia Commonwealth Rams': '/cbb/schools/virginia-commonwealth/',
    'Virginia Military Institute Keydets': '/cbb/schools/virginia-military-institute/',
    'Virginia Tech Hokies': '/cbb/schools/virginia-tech/',
    'Wagner Seahawks': '/cbb/schools/wagner/',
    'Wake Forest Demon Deacons': '/cbb/schools/wake-forest/',
    'Washington Huskies': '/cbb/schools/washington/',
    'Washington State Cougars': '/cbb/schools/washington-state/',
    'Weber State Wildcats': '/cbb/schools/weber-state/',
    'West Virginia Mountaineers': '/cbb/schools/west-virginia/',
    'Western Carolina Catamounts': '/cbb/schools/western-carolina/',
    'Western Illinois Leathernecks': '/cbb/schools/western-illinois/',
    'Western Kentucky Hilltoppers': '/cbb/schools/western-kentucky/',
    'Western Michigan Broncos': '/cbb/schools/western-michigan/',
    'Wichita State Shockers': '/cbb/schools/wichita-state/',
    'William & Mary Tribe': '/cbb/schools/william-mary/',
    'Winthrop Eagles': '/cbb/schools/winthrop/',
    'Wisconsin Badgers': '/cbb/schools/wisconsin/',
    'Wofford Terriers': '/cbb/schools/wofford/',
    'Wright State Raiders': '/cbb/schools/wright-state/',
    'Wyoming Cowboys': '/cbb/schools/wyoming/',
    'Xavier Musketeers': '/cbb/schools/xavier/',
    'Yale Bulldogs': '/cbb/schools/yale/',
    'Youngstown State Penguins': '/cbb/schools/youngstown-state/'
}
